// Code generated by protoc-gen-go. DO NOT EDIT.
// source: main.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	main.proto

It has these top-level messages:
	Image
	TransformedImage
	TransformImageRequest
	RotateImageRequest
	BlurImageRequest
	CropImageRequest
	NewTokenRequest
	DeleteTokenRequest
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type TransformationType int32

const (
	TransformationType_ROTATE TransformationType = 0
	TransformationType_CROP   TransformationType = 1
	TransformationType_BLUR   TransformationType = 2
)

var TransformationType_name = map[int32]string{
	0: "ROTATE",
	1: "CROP",
	2: "BLUR",
}
var TransformationType_value = map[string]int32{
	"ROTATE": 0,
	"CROP":   1,
	"BLUR":   2,
}

func (x TransformationType) String() string {
	return proto1.EnumName(TransformationType_name, int32(x))
}
func (TransformationType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Image struct {
	Size   int64  `protobuf:"varint,1,opt,name=size" json:"size,omitempty"`
	Format string `protobuf:"bytes,2,opt,name=format" json:"format,omitempty"`
	File   []byte `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
}

func (m *Image) Reset()                    { *m = Image{} }
func (m *Image) String() string            { return proto1.CompactTextString(m) }
func (*Image) ProtoMessage()               {}
func (*Image) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Image) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Image) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *Image) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

type TransformedImage struct {
	File []byte `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
}

func (m *TransformedImage) Reset()                    { *m = TransformedImage{} }
func (m *TransformedImage) String() string            { return proto1.CompactTextString(m) }
func (*TransformedImage) ProtoMessage()               {}
func (*TransformedImage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TransformedImage) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

type TransformImageRequest struct {
	Type  TransformationType   `protobuf:"varint,1,opt,name=type,enum=proto.TransformationType" json:"type,omitempty"`
	Data  *google_protobuf.Any `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	Image *Image               `protobuf:"bytes,3,opt,name=image" json:"image,omitempty"`
}

func (m *TransformImageRequest) Reset()                    { *m = TransformImageRequest{} }
func (m *TransformImageRequest) String() string            { return proto1.CompactTextString(m) }
func (*TransformImageRequest) ProtoMessage()               {}
func (*TransformImageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TransformImageRequest) GetType() TransformationType {
	if m != nil {
		return m.Type
	}
	return TransformationType_ROTATE
}

func (m *TransformImageRequest) GetData() *google_protobuf.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *TransformImageRequest) GetImage() *Image {
	if m != nil {
		return m.Image
	}
	return nil
}

type RotateImageRequest struct {
	Angle     int32 `protobuf:"varint,1,opt,name=angle" json:"angle,omitempty"`
	ClockWise bool  `protobuf:"varint,2,opt,name=clockWise" json:"clockWise,omitempty"`
}

func (m *RotateImageRequest) Reset()                    { *m = RotateImageRequest{} }
func (m *RotateImageRequest) String() string            { return proto1.CompactTextString(m) }
func (*RotateImageRequest) ProtoMessage()               {}
func (*RotateImageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RotateImageRequest) GetAngle() int32 {
	if m != nil {
		return m.Angle
	}
	return 0
}

func (m *RotateImageRequest) GetClockWise() bool {
	if m != nil {
		return m.ClockWise
	}
	return false
}

type BlurImageRequest struct {
	Sigma float32 `protobuf:"fixed32,1,opt,name=sigma" json:"sigma,omitempty"`
}

func (m *BlurImageRequest) Reset()                    { *m = BlurImageRequest{} }
func (m *BlurImageRequest) String() string            { return proto1.CompactTextString(m) }
func (*BlurImageRequest) ProtoMessage()               {}
func (*BlurImageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *BlurImageRequest) GetSigma() float32 {
	if m != nil {
		return m.Sigma
	}
	return 0
}

type CropImageRequest struct {
	TopLeftX int32 `protobuf:"varint,1,opt,name=topLeftX" json:"topLeftX,omitempty"`
	TopLeftY int32 `protobuf:"varint,2,opt,name=topLeftY" json:"topLeftY,omitempty"`
	Width    int32 `protobuf:"varint,3,opt,name=width" json:"width,omitempty"`
	Height   int32 `protobuf:"varint,4,opt,name=height" json:"height,omitempty"`
}

func (m *CropImageRequest) Reset()                    { *m = CropImageRequest{} }
func (m *CropImageRequest) String() string            { return proto1.CompactTextString(m) }
func (*CropImageRequest) ProtoMessage()               {}
func (*CropImageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CropImageRequest) GetTopLeftX() int32 {
	if m != nil {
		return m.TopLeftX
	}
	return 0
}

func (m *CropImageRequest) GetTopLeftY() int32 {
	if m != nil {
		return m.TopLeftY
	}
	return 0
}

func (m *CropImageRequest) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *CropImageRequest) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type NewTokenRequest struct {
	Label string `protobuf:"bytes,1,opt,name=label" json:"label,omitempty"`
}

func (m *NewTokenRequest) Reset()                    { *m = NewTokenRequest{} }
func (m *NewTokenRequest) String() string            { return proto1.CompactTextString(m) }
func (*NewTokenRequest) ProtoMessage()               {}
func (*NewTokenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *NewTokenRequest) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

type DeleteTokenRequest struct {
	Label string `protobuf:"bytes,1,opt,name=label" json:"label,omitempty"`
}

func (m *DeleteTokenRequest) Reset()                    { *m = DeleteTokenRequest{} }
func (m *DeleteTokenRequest) String() string            { return proto1.CompactTextString(m) }
func (*DeleteTokenRequest) ProtoMessage()               {}
func (*DeleteTokenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *DeleteTokenRequest) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func init() {
	proto1.RegisterType((*Image)(nil), "proto.Image")
	proto1.RegisterType((*TransformedImage)(nil), "proto.TransformedImage")
	proto1.RegisterType((*TransformImageRequest)(nil), "proto.TransformImageRequest")
	proto1.RegisterType((*RotateImageRequest)(nil), "proto.RotateImageRequest")
	proto1.RegisterType((*BlurImageRequest)(nil), "proto.BlurImageRequest")
	proto1.RegisterType((*CropImageRequest)(nil), "proto.CropImageRequest")
	proto1.RegisterType((*NewTokenRequest)(nil), "proto.NewTokenRequest")
	proto1.RegisterType((*DeleteTokenRequest)(nil), "proto.DeleteTokenRequest")
	proto1.RegisterEnum("proto.TransformationType", TransformationType_name, TransformationType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for IMage service

type IMageClient interface {
	TransformImage(ctx context.Context, opts ...grpc.CallOption) (IMage_TransformImageClient, error)
}

type iMageClient struct {
	cc *grpc.ClientConn
}

func NewIMageClient(cc *grpc.ClientConn) IMageClient {
	return &iMageClient{cc}
}

func (c *iMageClient) TransformImage(ctx context.Context, opts ...grpc.CallOption) (IMage_TransformImageClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_IMage_serviceDesc.Streams[0], c.cc, "/proto.IMage/TransformImage", opts...)
	if err != nil {
		return nil, err
	}
	x := &iMageTransformImageClient{stream}
	return x, nil
}

type IMage_TransformImageClient interface {
	Send(*TransformImageRequest) error
	Recv() (*TransformedImage, error)
	grpc.ClientStream
}

type iMageTransformImageClient struct {
	grpc.ClientStream
}

func (x *iMageTransformImageClient) Send(m *TransformImageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *iMageTransformImageClient) Recv() (*TransformedImage, error) {
	m := new(TransformedImage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for IMage service

type IMageServer interface {
	TransformImage(IMage_TransformImageServer) error
}

func RegisterIMageServer(s *grpc.Server, srv IMageServer) {
	s.RegisterService(&_IMage_serviceDesc, srv)
}

func _IMage_TransformImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IMageServer).TransformImage(&iMageTransformImageServer{stream})
}

type IMage_TransformImageServer interface {
	Send(*TransformedImage) error
	Recv() (*TransformImageRequest, error)
	grpc.ServerStream
}

type iMageTransformImageServer struct {
	grpc.ServerStream
}

func (x *iMageTransformImageServer) Send(m *TransformedImage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *iMageTransformImageServer) Recv() (*TransformImageRequest, error) {
	m := new(TransformImageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _IMage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.IMage",
	HandlerType: (*IMageServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TransformImage",
			Handler:       _IMage_TransformImage_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "main.proto",
}

func init() { proto1.RegisterFile("main.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 429 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x51, 0x6f, 0xd3, 0x30,
	0x10, 0xc7, 0x71, 0x97, 0x54, 0xed, 0x6d, 0x1a, 0x91, 0x35, 0xa0, 0xab, 0xf6, 0x50, 0xf9, 0x01,
	0xa2, 0x49, 0x64, 0xa8, 0xf0, 0x05, 0xb6, 0x81, 0x60, 0x62, 0x30, 0x64, 0x05, 0xc1, 0x1e, 0xdd,
	0xf5, 0x9a, 0x5a, 0x4b, 0xe3, 0x90, 0xb8, 0x1a, 0xe1, 0x73, 0xf0, 0x81, 0x51, 0xce, 0x21, 0x4d,
	0xcb, 0x03, 0x4f, 0xf1, 0xdf, 0xf7, 0xd3, 0xfd, 0xff, 0x17, 0x1f, 0xc0, 0x4a, 0xe9, 0x2c, 0xca,
	0x0b, 0x63, 0x0d, 0xf7, 0xe9, 0x33, 0x3e, 0x4e, 0x8c, 0x49, 0x52, 0x3c, 0x23, 0x35, 0x5b, 0x2f,
	0xce, 0x54, 0x56, 0x39, 0x42, 0xbc, 0x07, 0xff, 0x6a, 0xa5, 0x12, 0xe4, 0x1c, 0xbc, 0x52, 0xff,
	0xc2, 0x11, 0x9b, 0xb0, 0x70, 0x4f, 0xd2, 0x99, 0x3f, 0x85, 0xfe, 0xc2, 0x14, 0x2b, 0x65, 0x47,
	0xbd, 0x09, 0x0b, 0x87, 0xb2, 0x51, 0x35, 0xbb, 0xd0, 0x29, 0x8e, 0xf6, 0x26, 0x2c, 0x3c, 0x90,
	0x74, 0x16, 0xcf, 0x21, 0x88, 0x0b, 0x95, 0x95, 0x35, 0x82, 0xf3, 0xb6, 0x27, 0x71, 0xac, 0xc3,
	0xfd, 0x66, 0xf0, 0xa4, 0x05, 0x09, 0x93, 0xf8, 0x63, 0x8d, 0xa5, 0xe5, 0x2f, 0xc1, 0xb3, 0x55,
	0xee, 0xe8, 0xc3, 0xe9, 0xb1, 0x0b, 0x18, 0xb5, 0xac, 0xb2, 0xda, 0x64, 0x71, 0x95, 0xa3, 0x24,
	0x8c, 0x87, 0xe0, 0xcd, 0x95, 0x55, 0x14, 0x6d, 0x7f, 0x7a, 0x14, 0xb9, 0x19, 0xa3, 0xbf, 0x33,
	0x46, 0xe7, 0x59, 0x25, 0x89, 0xe0, 0x02, 0x7c, 0x5d, 0x1b, 0x51, 0xde, 0xfd, 0xe9, 0x41, 0xd3,
	0xd9, 0x99, 0xbb, 0x92, 0xf8, 0x00, 0x5c, 0x1a, 0xab, 0x2c, 0x6e, 0x45, 0x3a, 0x02, 0x5f, 0x65,
	0x49, 0x33, 0x81, 0x2f, 0x9d, 0xe0, 0x27, 0x30, 0xbc, 0x4b, 0xcd, 0xdd, 0xfd, 0x37, 0x5d, 0x22,
	0xd9, 0x0f, 0xe4, 0xe6, 0x42, 0x84, 0x10, 0x5c, 0xa4, 0xeb, 0x62, 0xb7, 0x4f, 0xa9, 0x93, 0x95,
	0xa2, 0x3e, 0x3d, 0xe9, 0x84, 0xf8, 0x09, 0xc1, 0x65, 0x61, 0xf2, 0x2d, 0x72, 0x0c, 0x03, 0x6b,
	0xf2, 0x6b, 0x5c, 0xd8, 0xef, 0x8d, 0x69, 0xab, 0x3b, 0xb5, 0x5b, 0xb2, 0xdd, 0xd4, 0x6e, 0x6b,
	0x87, 0x07, 0x3d, 0xb7, 0x4b, 0x9a, 0xd1, 0x97, 0x4e, 0xd4, 0x0f, 0xb8, 0x44, 0x9d, 0x2c, 0xed,
	0xc8, 0xa3, 0xeb, 0x46, 0x89, 0x17, 0xf0, 0xf8, 0x33, 0x3e, 0xc4, 0xe6, 0x1e, 0xb3, 0x4e, 0xc4,
	0x54, 0xcd, 0x30, 0x25, 0xd7, 0xa1, 0x74, 0x42, 0x9c, 0x02, 0x7f, 0x8b, 0x29, 0x5a, 0xfc, 0x3f,
	0x7b, 0xfa, 0x06, 0xf8, 0xbf, 0x8f, 0xc5, 0x01, 0xfa, 0xf2, 0x26, 0x3e, 0x8f, 0xdf, 0x05, 0x8f,
	0xf8, 0x00, 0xbc, 0x4b, 0x79, 0xf3, 0x25, 0x60, 0xf5, 0xe9, 0xe2, 0xfa, 0xab, 0x0c, 0x7a, 0xd3,
	0x18, 0xfc, 0xab, 0x4f, 0xf5, 0xb2, 0x7c, 0x84, 0xc3, 0xed, 0xbd, 0xe0, 0x27, 0xbb, 0x2b, 0xd0,
	0xfd, 0x53, 0xe3, 0x67, 0xbb, 0xd5, 0x66, 0xeb, 0x42, 0xf6, 0x8a, 0xcd, 0xfa, 0x54, 0x7b, 0xfd,
	0x27, 0x00, 0x00, 0xff, 0xff, 0xc6, 0x0c, 0xa4, 0x5e, 0x0d, 0x03, 0x00, 0x00,
}
